# Generated by Django 4.2.7 on 2024-05-21 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reshebergement',
            name='Courrier',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ressalle',
            name='idressalle',
            field=models.OneToOneField(db_column='idressalle', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='ressalle_idressalle', serialize=False, to='guesthouse.ressalle'),
        ),
    ]
