# Generated by Django 4.2.7 on 2024-05-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0002_alter_reshebergement_courrier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressalle',
            name='idressalle',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
