# Generated by Django 4.2.7 on 2024-05-24 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0003_alter_ressalle_idressalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reshebergement',
            name='dateHebergement',
        ),
    ]
